export type Plan = 'Starter' | 'Growth' | 'Pro';
export type SubscriberStatus = 'active' | 'overdue' | 'risk' | 'trial' | 'canceled';

export interface Invoice {
  reference: string;
  amountBrl: number;
  status: 'paid' | 'open' | 'overdue' | 'refunded';
  dueDate: string;
}

export type LeadOrigin =
  | 'site'
  | 'indicacao'
  | 'instagram'
  | 'whatsapp'
  | 'meta_ads'
  | 'google_ads'
  | 'evento'
  | 'outro';

export interface Subscriber {
  id: string;
  name: string;
  email: string;
  plan: Plan;
  mrrBrl: number | null;
  status: SubscriberStatus;
  lastLoginRelative: string;
  customerSince: string;
  customerSinceDays: number;
  channels: string[];
  agentsCount: number;
  messages30d: number;
  llmCostMonthUsd: number;
  marginPct: number;
  invoices: Invoice[];

  // Cadastrais · base de lead → cliente
  razaoSocial?: string;
  cnpj?: string;
  telefone?: string;
  cidade?: string;
  uf?: string;
  segmento?: string;
  origem?: LeadOrigin;
  origemDetalhe?: string;
  notas?: string;
}

const PLAN_PRICE: Record<Plan, number> = {
  Starter: 297,
  Growth: 597,
  Pro: 1297,
};

export const subscribersMock: Subscriber[] = [
  {
    id: 'sub_001',
    name: 'Imobiliária Capital',
    email: 'contato@imobcapital.com.br',
    plan: 'Pro',
    mrrBrl: PLAN_PRICE.Pro,
    status: 'active',
    lastLoginRelative: '2h atrás',
    customerSince: '18/03/2026',
    customerSinceDays: 50,
    channels: ['WhatsApp', 'Instagram'],
    agentsCount: 4,
    messages30d: 3412,
    llmCostMonthUsd: 42.8,
    marginPct: 73,
    invoices: [
      { reference: 'Mai/26', amountBrl: 1297, status: 'open', dueDate: '12/05/2026' },
      { reference: 'Abr/26', amountBrl: 1297, status: 'paid', dueDate: '12/04/2026' },
      { reference: 'Mar/26', amountBrl: 1297, status: 'paid', dueDate: '18/03/2026' },
    ],
    razaoSocial: 'Imobiliária Capital Negócios Imobiliários LTDA',
    cnpj: '32.114.586/0001-09',
    telefone: '5561999441100',
    cidade: 'Brasília',
    uf: 'DF',
    segmento: 'Imobiliário',
    origem: 'meta_ads',
    origemDetalhe: 'Campanha "Atendimento 24h" · Mar/26',
    notas: 'Operava 3 corretores manuais · adotou Pro pra automatizar prospecção via DM Instagram.',
  },
  {
    id: 'sub_002',
    name: 'Auto Escola Norte',
    email: 'gerencia@aenorte.com.br',
    plan: 'Growth',
    mrrBrl: PLAN_PRICE.Growth,
    status: 'active',
    lastLoginRelative: 'ontem',
    customerSince: '02/04/2026',
    customerSinceDays: 35,
    channels: ['WhatsApp'],
    agentsCount: 2,
    messages30d: 1823,
    llmCostMonthUsd: 18.4,
    marginPct: 68,
    invoices: [
      { reference: 'Mai/26', amountBrl: 597, status: 'open', dueDate: '15/05/2026' },
      { reference: 'Abr/26', amountBrl: 597, status: 'paid', dueDate: '15/04/2026' },
    ],
    razaoSocial: 'Centro de Formação de Condutores Norte LTDA',
    cnpj: '11.987.450/0001-22',
    telefone: '5547988221145',
    cidade: 'Joinville',
    uf: 'SC',
    segmento: 'Educação',
    origem: 'indicacao',
    origemDetalhe: 'Indicação de Studio Beauty Marília',
    notas: 'Foco em qualificar primeiro contato e agendar matrícula.',
  },
  {
    id: 'sub_003',
    name: 'Clínica Sorriso Mais',
    email: 'recepcao@sorrisomais.com.br',
    plan: 'Growth',
    mrrBrl: PLAN_PRICE.Growth,
    status: 'active',
    lastLoginRelative: '1h atrás',
    customerSince: '10/04/2026',
    customerSinceDays: 27,
    channels: ['WhatsApp', 'Instagram'],
    agentsCount: 3,
    messages30d: 2104,
    llmCostMonthUsd: 22.1,
    marginPct: 64,
    invoices: [
      { reference: 'Mai/26', amountBrl: 597, status: 'open', dueDate: '18/05/2026' },
      { reference: 'Abr/26', amountBrl: 597, status: 'paid', dueDate: '10/04/2026' },
    ],
    razaoSocial: 'Clínica Sorriso Mais Odontologia LTDA',
    cnpj: '24.778.103/0001-76',
    telefone: '5511944332211',
    cidade: 'Campinas',
    uf: 'SP',
    segmento: 'Saúde',
    origem: 'site',
    origemDetalhe: 'Form lp /pix · vídeo demo',
    notas: 'Atende WhatsApp + IG · pediu integração com agenda.',
  },
  {
    id: 'sub_004',
    name: 'Energia Solar BH',
    email: 'comercial@energiasolarbh.com.br',
    plan: 'Growth',
    mrrBrl: PLAN_PRICE.Growth,
    status: 'overdue',
    lastLoginRelative: '3d atrás',
    customerSince: '05/03/2026',
    customerSinceDays: 63,
    channels: ['WhatsApp'],
    agentsCount: 2,
    messages30d: 1567,
    llmCostMonthUsd: 16.8,
    marginPct: 70,
    invoices: [
      { reference: 'Mai/26', amountBrl: 597, status: 'overdue', dueDate: '05/05/2026' },
      { reference: 'Abr/26', amountBrl: 597, status: 'paid', dueDate: '05/04/2026' },
      { reference: 'Mar/26', amountBrl: 597, status: 'paid', dueDate: '05/03/2026' },
    ],
    razaoSocial: 'BH Solar Energia Renovável LTDA',
    cnpj: '08.456.991/0001-44',
    telefone: '5531983322110',
    cidade: 'Belo Horizonte',
    uf: 'MG',
    segmento: 'Energia Solar',
    origem: 'google_ads',
    origemDetalhe: 'Campanha keywords "energia solar BH"',
    notas: 'Pagamento atrasou em Mai · enviar lembrete amigável.',
  },
  {
    id: 'sub_005',
    name: 'Studio Beauty Marília',
    email: 'agendamento@beautymarilia.com.br',
    plan: 'Starter',
    mrrBrl: PLAN_PRICE.Starter,
    status: 'active',
    lastLoginRelative: '30 min',
    customerSince: '15/04/2026',
    customerSinceDays: 22,
    channels: ['Instagram'],
    agentsCount: 1,
    messages30d: 412,
    llmCostMonthUsd: 4.2,
    marginPct: 60,
    invoices: [
      { reference: 'Mai/26', amountBrl: 297, status: 'open', dueDate: '20/05/2026' },
      { reference: 'Abr/26', amountBrl: 297, status: 'paid', dueDate: '20/04/2026' },
    ],
    razaoSocial: 'Studio Marília Estética & Beleza LTDA ME',
    cnpj: '36.221.488/0001-15',
    telefone: '5514998877665',
    cidade: 'Marília',
    uf: 'SP',
    segmento: 'Beleza',
    origem: 'instagram',
    origemDetalhe: 'DM · após reels com 8k views',
    notas: 'Indicou Auto Escola Norte. Top NPS.',
  },
  {
    id: 'sub_006',
    name: 'Açaí do Bairro',
    email: 'contato@acaidobairro.com.br',
    plan: 'Starter',
    mrrBrl: PLAN_PRICE.Starter,
    status: 'active',
    lastLoginRelative: 'ontem',
    customerSince: '20/04/2026',
    customerSinceDays: 17,
    channels: ['WhatsApp'],
    agentsCount: 1,
    messages30d: 287,
    llmCostMonthUsd: 3.1,
    marginPct: 58,
    invoices: [
      { reference: 'Mai/26', amountBrl: 297, status: 'open', dueDate: '22/05/2026' },
    ],
    razaoSocial: 'Açaí do Bairro Comércio de Alimentos LTDA',
    cnpj: '52.118.097/0001-83',
    telefone: '5521977665544',
    cidade: 'Niterói',
    uf: 'RJ',
    segmento: 'Alimentação',
    origem: 'site',
    origemDetalhe: 'Trial via /pix landing',
    notas: 'Quer integração com iFood (não temos ainda).',
  },
  {
    id: 'sub_007',
    name: 'Mercadinho da Vila',
    email: 'pedidos@mercadinhovila.com.br',
    plan: 'Starter',
    mrrBrl: PLAN_PRICE.Starter,
    status: 'active',
    lastLoginRelative: '3h atrás',
    customerSince: '25/04/2026',
    customerSinceDays: 12,
    channels: ['WhatsApp'],
    agentsCount: 1,
    messages30d: 198,
    llmCostMonthUsd: 2.4,
    marginPct: 56,
    invoices: [
      { reference: 'Mai/26', amountBrl: 297, status: 'open', dueDate: '25/05/2026' },
    ],
    razaoSocial: 'Mercadinho da Vila Comércio Varejista LTDA',
    cnpj: '17.882.301/0001-60',
    telefone: '5511988774422',
    cidade: 'São Paulo',
    uf: 'SP',
    segmento: 'Varejo',
    origem: 'whatsapp',
    origemDetalhe: 'Mensagem direta após ver post Cris',
    notas: 'Bairro Vila Mariana. Atende delivery local.',
  },
  {
    id: 'sub_008',
    name: 'Tatuagem Negra Tinta',
    email: 'studio@negratinta.com.br',
    plan: 'Starter',
    mrrBrl: null,
    status: 'trial',
    lastLoginRelative: 'hoje',
    customerSince: '01/05/2026',
    customerSinceDays: 6,
    channels: ['Instagram'],
    agentsCount: 1,
    messages30d: 89,
    llmCostMonthUsd: 0.8,
    marginPct: 0,
    invoices: [],
    razaoSocial: 'Negra Tinta Studio Tatuagem ME',
    cnpj: '49.776.220/0001-31',
    telefone: '5511955667788',
    cidade: 'São Paulo',
    uf: 'SP',
    segmento: 'Estúdio Criativo',
    origem: 'instagram',
    origemDetalhe: 'Reel "como atender no DM"',
    notas: 'Trial inicia hoje. Conferir engagement em D+3.',
  },
  {
    id: 'sub_009',
    name: 'Lava-Rápido Express',
    email: 'agendamentos@lavarapidoexpress.com.br',
    plan: 'Growth',
    mrrBrl: null,
    status: 'trial',
    lastLoginRelative: 'hoje',
    customerSince: '03/05/2026',
    customerSinceDays: 4,
    channels: ['WhatsApp'],
    agentsCount: 2,
    messages30d: 67,
    llmCostMonthUsd: 0.6,
    marginPct: 0,
    invoices: [],
    razaoSocial: 'Express Lava-Rápido Serviços Automotivos LTDA',
    cnpj: '40.998.122/0001-77',
    telefone: '5519988445566',
    cidade: 'Campinas',
    uf: 'SP',
    segmento: 'Automotivo',
    origem: 'meta_ads',
    origemDetalhe: 'Lookalike base whatsapp',
    notas: 'Avaliando upgrade pra Growth · pediu mais 1 canal.',
  },
  {
    id: 'sub_010',
    name: 'Pet Shop Bichano',
    email: 'atendimento@petshopbichano.com.br',
    plan: 'Growth',
    mrrBrl: PLAN_PRICE.Growth,
    status: 'risk',
    lastLoginRelative: '11d atrás',
    customerSince: '12/03/2026',
    customerSinceDays: 56,
    channels: ['WhatsApp'],
    agentsCount: 2,
    messages30d: 12,
    llmCostMonthUsd: 0.3,
    marginPct: 99,
    invoices: [
      { reference: 'Mai/26', amountBrl: 597, status: 'open', dueDate: '28/05/2026' },
      { reference: 'Abr/26', amountBrl: 597, status: 'paid', dueDate: '12/04/2026' },
    ],
    razaoSocial: 'Pet Shop Bichano Comércio e Serviços ME',
    cnpj: '28.554.667/0001-12',
    telefone: '5511988002211',
    cidade: 'Guarulhos',
    uf: 'SP',
    segmento: 'Pet',
    origem: 'indicacao',
    origemDetalhe: 'Indicado por Imobiliária Capital',
    notas: 'Sumiu há 11d · risco de churn · agendar ligação.',
  },
  {
    id: 'sub_011',
    name: 'Padaria Pão Quente',
    email: 'pedidos@paoquente.com.br',
    plan: 'Starter',
    mrrBrl: PLAN_PRICE.Starter,
    status: 'active',
    lastLoginRelative: '5h atrás',
    customerSince: '28/04/2026',
    customerSinceDays: 9,
    channels: ['WhatsApp'],
    agentsCount: 1,
    messages30d: 156,
    llmCostMonthUsd: 1.9,
    marginPct: 55,
    invoices: [
      { reference: 'Mai/26', amountBrl: 297, status: 'open', dueDate: '28/05/2026' },
    ],
    razaoSocial: 'Padaria Pão Quente do Bairro LTDA ME',
    cnpj: '15.226.443/0001-08',
    telefone: '5511933445566',
    cidade: 'Osasco',
    uf: 'SP',
    segmento: 'Alimentação',
    origem: 'site',
    origemDetalhe: 'Form lp · trial 7d',
    notas: 'Pedidos por WA + Pix automatizado.',
  },
  {
    id: 'sub_012',
    name: 'Academia Fitness Pro',
    email: 'recepcao@fitnesspro.com.br',
    plan: 'Pro',
    mrrBrl: PLAN_PRICE.Pro,
    status: 'active',
    lastLoginRelative: '4h atrás',
    customerSince: '22/03/2026',
    customerSinceDays: 46,
    channels: ['WhatsApp', 'Instagram'],
    agentsCount: 5,
    messages30d: 4218,
    llmCostMonthUsd: 58.2,
    marginPct: 41,
    invoices: [
      { reference: 'Mai/26', amountBrl: 1297, status: 'open', dueDate: '22/05/2026' },
      { reference: 'Abr/26', amountBrl: 1297, status: 'paid', dueDate: '22/04/2026' },
    ],
    razaoSocial: 'Academia Fitness Pro Treinamento Esportivo LTDA',
    cnpj: '63.110.992/0001-50',
    telefone: '5511966554433',
    cidade: 'São Paulo',
    uf: 'SP',
    segmento: 'Fitness',
    origem: 'evento',
    origemDetalhe: 'Imersão Cris · Fev/26',
    notas: 'Custo LLM disparado · revisar prompts dos agentes.',
  },
  {
    id: 'sub_canceled_01',
    name: 'Bistrô Mediterrâneo',
    email: 'reservas@mediterraneo.com.br',
    plan: 'Growth',
    mrrBrl: null,
    status: 'canceled',
    lastLoginRelative: '22d atrás',
    customerSince: '10/02/2026',
    customerSinceDays: 86,
    channels: [],
    agentsCount: 0,
    messages30d: 0,
    llmCostMonthUsd: 0,
    marginPct: 0,
    invoices: [
      { reference: 'Abr/26', amountBrl: 597, status: 'paid', dueDate: '10/04/2026' },
      { reference: 'Mar/26', amountBrl: 597, status: 'paid', dueDate: '10/03/2026' },
    ],
    razaoSocial: 'Bistrô Mediterrâneo Restaurante LTDA',
    cnpj: '74.557.881/0001-29',
    telefone: '5511944778899',
    cidade: 'São Paulo',
    uf: 'SP',
    segmento: 'Gastronomia',
    origem: 'site',
    origemDetalhe: 'Form contato',
    notas: 'Cancelou em Abr · motivo: equipe não bateu com WhatsApp Business.',
  },
];

export const SUBSCRIBERS_STATS = {
  active: subscribersMock.filter((s) => ['active', 'overdue', 'risk'].includes(s.status)).length,
  trial: subscribersMock.filter((s) => s.status === 'trial').length,
  canceled: subscribersMock.filter((s) => s.status === 'canceled').length,
};
